console.log("Hello World")
import os from 'os'
//const os=require("os")
console.log(os.type())
console.log(os.version())
console.log(os.homedir())
const path=require('path')
//console.log(global)
console.log(path.dirname(__filename))
console.log(path.basename(__filename))
console.log(path.parse(__filename))
const math=require('./math')
const {add,sub,mul,div}=require('./math')
console.log(math.add(2,7))
console.log(math.sub(2,7))
console.log(mul(2,7))
console.log(div(2,7))